import io from 'socket.io-client';
// ...
const socket = io('http://localhost:3001');
// ...
socket.on('user-connected', (userId) => {
  // ...
});
// ...
socket.emit('call-user', { signalData: data, targetUserId: userId });
// ...
socket.on('user-disconnected', (userId) => {
  // ...
});